### ISSUE TITLE
这项目还打算继续么？

### ISSUE THREAD

**Issue by iredmail** [dkluffy/noansible#1]
Hi @dkluffy 

对你的项目非常感兴趣，不知道是否还会继续开发和完善？

**Comment by dkluffy** [comment]
> Hi @dkluffy
> 
> 对你的项目非常感兴趣，不知道是否还会继续开发和完善？

目前就我自己在用，就算继续完善，进度也会很慢的。所以，不太建议用。

**Comment by iredmail** [comment]
方便加个私人联系方式聊聊这方面的开发么？我也在做一个类似的项目，但只支持本地操作，不支持 ssh。:)
Telegram：@iredmail
联系上后我会把上面的联系方式删除。
